-- Postgres 10 identity columns (i.e. those created with GENERATED BY DEFAULT AS IDENTITY) don’t have
-- ordinary default values (as reported by information_schema.columns.column_default), but we still
-- need them for the purposes of hdb_catalog.inject_table_defaults.
--
-- Internally, generated columns are backed by ordinary sequences. This view exposes them using the
-- same interface as information_schema.
CREATE VIEW hdb_catalog.hdb_columns_identity_default_values AS
  SELECT table_schema.nspname::text AS table_schema
       , table_class.relname::text AS table_name
       , identity_column.attname::text AS column_name
       , format('nextval(%L::regclass)', sequence.seqrelid::regclass)::text AS column_default
    FROM pg_sequence sequence
    JOIN pg_depend depend
          ON depend.classid = 'pg_class'::regclass
         AND depend.refclassid = 'pg_class'::regclass
         AND depend.objid = sequence.seqrelid
         AND depend.deptype = 'i'
    JOIN pg_attribute identity_column
          ON identity_column.attrelid = depend.refobjid
         AND identity_column.attnum = depend.refobjsubid
    JOIN pg_class table_class ON table_class.oid = identity_column.attrelid
    JOIN pg_namespace table_schema ON table_schema.oid = table_class.relnamespace;

CREATE OR REPLACE VIEW hdb_catalog.hdb_columns_default_values
     AS SELECT * FROM hdb_catalog.hdb_columns_ordinary_default_values
  UNION SELECT * FROM hdb_catalog.hdb_columns_identity_default_values;

-- TODO: Refresh any views that depend on tables with identity columns.
